-- CREATE TABLE IF NOT EXISTS navbar (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     title text NOT NULL,
--     url text NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS posts (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     email text NOT NULL,
--     text text NOT NULL,
--     time text NOT NULL,
--     url text NOT NULL,
--     titlepost text NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS users (
--     id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL,
--     email text NOT NULL,
--     password text NOT NULL,
--     ava BYTEA DEFAULT NULL,
--     time text NOT NULL,
--     PRIMARY KEY (id)
-- )

-- CREATE TABLE IF NOT EXISTS posts (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     titlepost text NOT NULL,
--     img BYTEA NOT NULL,
--     text text NOT NULL,
--     time text NOT NULL
-- );

CREATE TABLE IF NOT EXISTS dogs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    img BYTEA NOT NULL,
    time text NOT NULL
);
